<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BookingSeeder extends Seeder
{
    public function run()
    {
        // 'spot_id', 'customer_id', 'booking_date', 'visit_date', 'visit_time', 'num_adults', 'num_children', 'num_seniors', 'total_guests', 'price_per_person', 'subtotal', 'discount_amount', 'tax_amount', 'total_price', 'booking_status', 'payment_status', 'special_requests', 'cancellation_reason', 'internal_notes', 'created_at', 'updated_at', 'Confirmed_at', 'C_at', 'C_at'
        $data = [
            [
                'spot_id' => 1,
                'customer_id' => 1,
                'booking_date' => date('Y-m-d H:i:s'),
                'visit_date' => '2024-12-15',
                'visit_time' => '10:00:00',
                'num_adults' => 2,
                'num_children' => 1,
                'num_seniors' => 0,
                'total_guests' => 3,
                'price_per_person' => 500.00,
                'subtotal' => 1500.00,
                'discount_amount' => 0.00,
                'tax_amount' => 150.00,
                'total_price' => 1650.00,
                'booking_status' => 'Confirmed',
                'payment_status' => 'Paid',
                'special_requests' => 'Need wheelchair access',
                'cancellation_reason'=> null,
                'internal_notes' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
                 'confirmed_at' => null,
                 'cancelled_at' => null,
                 'completed_at' => null,
                'updated_at' => date('Y-m-d H:i:s'),
                
                
            ],
            [
                'spot_id' => 1,
                'customer_id' => 1,
                'booking_date' => date('Y-m-d H:i:s'),
                'visit_date' => '2025-09-16',
                'visit_time' => '14:00:00',
                'num_adults' => 1,
                'num_children' => 0,
                'num_seniors' => 1,
                'total_guests' => 2,
                'price_per_person' => 500.00,
                'subtotal' => 1000.00,
                'discount_amount' => 50.00,
                'tax_amount' => 95.00,
                'total_price' => 1045.00,
                'booking_status' => 'Pending',
                'payment_status' => 'Unpaid',
                'special_requests' => '',
                'cancellation_reason'=> null,
                'internal_notes' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
                 'confirmed_at' => null,
                 'cancelled_at' => null,
                 'completed_at' => null,
                
                
            ],

           
            [
                'spot_id' => 2,
                'customer_id' => 2,
                'booking_date' => date('Y-m-d H:i:s'),
                'visit_date' => '2024-10-05',
                'visit_time' => '11:30:00',
                'num_adults' => 2,
                'num_children' => 0,
                'num_seniors' => 2,
                'total_guests' => 4,
                'price_per_person' => 400.00,
                'subtotal' => 1600.00,
                'discount_amount' => 0.00,
                'tax_amount' => 160.00,
                'total_price' => 1760.00,
                'booking_status' => 'Cancelled',
                'payment_status' => 'Refunded',
                'special_requests' => '',
                'cancellation_reason' => 'Change of plans',
                'cancellation_reason'=> null,
                'internal_notes' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
                 'confirmed_at' => null,
                 'cancelled_at' => null,
                 'completed_at' => null,
                
                
            ],
            [
                'spot_id' => 3,
                'customer_id' => 3,
                'booking_date' => date('Y-m-d H:i:s'),
                'visit_date' => '2024-12-01',
                'visit_time' => '13:00:00',
                'num_adults' => 1,
                'num_children' => 1,
                'num_seniors' => 0,
                'total_guests' => 2,
                'price_per_person' => 600.00,
                'subtotal' => 1200.00,
                'discount_amount' => 0.00,
                'tax_amount' => 120.00,
                'total_price' => 1320.00,
                'booking_status' => 'Completed',
                'payment_status' => 'Paid',
                'special_requests' => 'Near the stage',
                'cancellation_reason'=> null,
                'internal_notes' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
                 'confirmed_at' => null,
                 'cancelled_at' => null,
                 'completed_at' => null,
                
                
            ],
           
            [
                'spot_id' => 4,
                'customer_id' => 4,
                'booking_date' => date('Y-m-d H:i:s'),
                'visit_date' => '2025-02-14',
                'visit_time' => '12:00:00',
                'num_adults' => 2,
                'num_children' => 2,
                'num_seniors' => 1,
                'total_guests' => 5,
                'price_per_person' => 550.00,
                'subtotal' => 2750.00,
                'discount_amount' => 200.00,
                'tax_amount' => 255.00,
                'total_price' => 2805.00,
                'booking_status' => 'Completed',
                'payment_status' => 'Unpaid',
                'special_requests' => 'High chair needed',
                
                'cancellation_reason'=> null,
                'internal_notes' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
                 'confirmed_at' => null,
                 'cancelled_at' => null,
                 'completed_at' => null,
               
                
                
            ],
           
            [
                'spot_id' => 5,
                'customer_id' => 5,
                'booking_date' => date('Y-m-d H:i:s'),
                'visit_date' => '2025-04-18',
                'visit_time' => '14:30:00',
                'num_adults' => 2,
                'num_children' => 0,
                'num_seniors' => 2,
                'total_guests' => 4,
                'price_per_person' => 400.00,
                'subtotal' => 1600.00,
                'discount_amount' => 80.00,
                'tax_amount' => 152.00,
                'total_price' => 1672.00,
                'booking_status' => 'Confirmed',
                'payment_status' => 'Paid',
                'special_requests' => 'Quiet area',
                'cancellation_reason'=> null,
                'internal_notes' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
                 'confirmed_at' => null,
                 'cancelled_at' => null,
                 'completed_at' => null,
                
                
            ], 
           
            [
                'spot_id' => 6,
                'customer_id' => 6,
                'booking_date' => date('Y-m-d H:i:s'),
                'visit_date'=> '2025-06-30',
                'visit_time' => '11:00:00',
                'num_adults' => 2,
                'num_children' => 2,
                'num_seniors' => 1,
                'total_guests' => 5,
                'price_per_person' => 550.00,
                'subtotal' => 2750.00,
                'discount_amount' => 150.00,
                'tax_amount' => 260.00,
                'total_price' => 2860.00,
                'booking_status' => 'Confirmed',
                'payment_status' => 'Unpaid',
                'special_requests' => 'Allergic to nuts',
                'cancellation_reason'=> null,
                'internal_notes' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
                 'confirmed_at' => null,
                 'cancelled_at' => null,
                 'completed_at' => null,
                
                

            ],
            [
                'spot_id' => 7,
                'customer_id' => 7,
                'booking_date' => date('Y-m-d H:i:s'),
                'visit_date' => '2025-08-12',
                'visit_time' => '15:00:00',
                'num_adults' => 1,
                'num_children' => 0,
                'num_seniors' => 1,
                'total_guests' => 2,
                'price_per_person' => 600.00,
                'subtotal' => 1200.00,
                'discount_amount' => 0.00,
                'tax_amount' => 120.00,
                'total_price' => 1320.00,
                'booking_status' => 'Confirmed',
                'payment_status' => 'Paid',
                'special_requests' => '',
                'cancellation_reason'=> null,
                'internal_notes' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
                 'confirmed_at' => null,
                 'cancelled_at' => null,
                 'completed_at' => null,
                
                
            ],
            [
                'spot_id' => 8,
                'customer_id' => 8,
                'booking_date' => date('Y-m-d H:i:s'),
                'visit_date' => '2024-11-20',
                'visit_time' => '09:30:00',
                'num_adults' => 3,
                'num_children' => 1,
                'num_seniors' => 0,
                'total_guests' => 4,
                'price_per_person' => 450.00,
                'subtotal' => 1800.00,
                'discount_amount' => 100.00,
                'tax_amount' => 170.00,
                'total_price' => 1870.00,
                'booking_status' => 'Confirmed',
                'payment_status' => 'Paid',
                'special_requests' => 'Vegetarian meals',
                'cancellation_reason'=> null,
                'internal_notes' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
                 'confirmed_at' => null,
                 'cancelled_at' => null,
                 'completed_at' => null,
                
                
            ],
            [
                'spot_id' => 9,
                'customer_id' => 9,
                'booking_date' => date('Y-m-d H:i:s'),
                'visit_date' => '2025-03-22',
                'visit_time' => '13:30:00',
                'num_adults' => 2,
                'num_children' => 2,
                'num_seniors' => 1,
                'total_guests' => 5,
                'price_per_person' => 500.00,
                'subtotal' => 2500.00,
                'discount_amount' => 200.00,
                'tax_amount' => 230.00,
                'total_price' => 2530.00,
                'booking_status' => 'Confirmed',
                'payment_status' => 'Unpaid',
                'special_requests' => '',
                'cancellation_reason'=> null,
                'internal_notes' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
                 'confirmed_at' => null,
                 'cancelled_at' => null,
                 'completed_at' => null,
                
                
            ],
            [
                'spot_id' => 10,
                'customer_id' => 10,
                'booking_date' => date('Y-m-d H:i:s'),
                'visit_date' => '2024-12-25',
                'visit_time' => '12:30:00',
                'num_adults' => 4,
                'num_children' => 0,
                'num_seniors' => 2,
                'total_guests' => 6,
                'price_per_person' => 600.00,
                'subtotal' => 3600.00,
                'discount_amount' => 300.00,
                'tax_amount' => 330.00,
                'total_price' => 3630.00,
                'booking_status' => 'Confirmed',
                'payment_status' => 'Paid',
                'special_requests' => 'Window seats',
                'cancellation_reason'=> null,
                'internal_notes' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => null,
                 'confirmed_at' => null,
                 'cancelled_at' => null,
                 'completed_at' => null,
                
                
            ]

        ];
        $this->db->table('bookings')->insertBatch($data);
    }
}
