<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class TouristSpotSeeder extends Seeder
{
    public function run()
    {
        //'business_id', 'spot_name', 'description', 'category', 'location', 'latitude', 'longitude', 'capacity', 'opening_time', 'closing_time', 'operating_days', 'status', 'price_per_person', 'child_price', 'senior_price', 'group_discount_percent', 'primary_image', 'average_rating', 'total_reviews', 'popularity_score', 'created_at', 'updated_at'

        $data = [
            [
                'business_id' => 1,
                'spot_name' => 'Ancient Ruins Park',
                'description' => 'Explore the remnants of an ancient civilization with guided tours and interactive exhibits.',
                'category' => 'Historical',
                'location' => '123 Heritage St, Nasugbo City',
                'capacity' => 200,
                'opening_time' => '08:00:00',
                'closing_time' => '18:00:00',
                'operating_days' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
                'status' => 'pending',
                'price_per_person' => 300.00,
                'child_price' => 150.00,
                'senior_price' => 200.00,
                'group_discount_percent' => 10.00,
                'primary_image' => 'ancient_ruins.jpg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'business_id' => 1,
                'spot_name' => 'Sunset Beach',
                'description' => 'Relax on the golden sands and enjoy breathtaking sunsets at our pristine beach.',
                'category' => 'Nature',
                'location' => '456 Ocean Ave, Nasugbo City',
                'capacity' => 500,
                'opening_time' => '06:00:00',
                'closing_time' => '20:00:00',
                'operating_days' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
                'status' => 'approved',
                'price_per_person' => 0.00,
                'child_price' => 0.00,
                'senior_price' => 0.00,
                'group_discount_percent' => 0.00,
                'primary_image' => 'sunset_beach.jpg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'business_id' => 2,
                'spot_name' => 'Mountain Adventure Park',
                'description' => 'Experience thrilling outdoor activities like zip-lining, rock climbing, and hiking trails.',
                'category' => 'Adventure',
                'location' => '789 Summit Rd, Nasugbo City',
                'capacity' => 150,
                'opening_time' => '09:00:00',
                'closing_time' => '17:00:00',
                'operating_days' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
                'status' => 'approved',
                'price_per_person' => 500.00,
                'child_price' => 250.00,
                'senior_price' => 300.00,
                'group_discount_percent' => 15.00,
                'primary_image' => 'mountain_adventure.jpg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'business_id' => 3,
                'spot_name' => 'Calayo Beach',
                'description' => 'A peaceful beach with soft sand, calm waves, and local fishing village charm — perfect for relaxation.',
                'category' => 'Beach',
                'location' => 'Calayo, Nasugbu, Batangas',
                'capacity' => 400,
                'opening_time' => '06:00:00',
                'closing_time' => '20:00:00',
                'operating_days' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
                'status' => 'approved',
                'price_per_person' => 100.00,
                'child_price' => 70.00,
                'senior_price' => 80.00,
                'group_discount_percent' => 10.00,
                'primary_image' => 'calayo_beach.jpg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
             ],
             [
                'business_id' => 4,
                'spot_name' => 'Canyon Cove Beach Resort',
                'description' => 'A family-friendly resort with white sand beach, infinity pool, and various water sports.',
                'category' => 'Resort',
                'location' => 'Far East Road, Piloto Wawa, Nasugbu, Batangas',
                'capacity' => 800,
                'opening_time' => '07:00:00',
                'closing_time' => '22:00:00',
                'operating_days' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
                'status' => 'approved',
                'price_per_person' => 500.00,
                'child_price' => 300.00,
                'senior_price' => 400.00,
                'group_discount_percent' => 15.00,
                'primary_image' => 'canyon_cove.jpg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
              ],
               [
                'business_id' => 5,
                'spot_name' => 'Tali Beach',
                'description' => 'A private seaside community famous for cliff diving, swimming, and relaxing views.',
                'category' => 'Beach',
                'location' => 'Tali Beach Subdivision, Nasugbu, Batangas',
                'capacity' => 250,
                'opening_time' => '06:00:00',
                'closing_time' => '19:00:00',
                'operating_days' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
                'status' => 'approved',
                'price_per_person' => 300.00,
                'child_price' => 200.00,
                'senior_price' => 250.00,
                'group_discount_percent' => 5.00,
                'primary_image' => 'tali_beach.jpg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'business_id' => 6,
                'spot_name' => 'Mount Talamitam',
                'description' => 'A beginner-friendly hiking trail with panoramic views and a peaceful summit area.',
                'category' => 'Nature',
                'location' => 'Sitio Bayabasan, Nasugbu, Batangas',
                'capacity' => 150,
                'opening_time' => '05:00:00',
                'closing_time' => '17:00:00',
                'operating_days' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
                'status' => 'approved',
                'price_per_person' => 40.00,
                'child_price' => 20.00,
                'senior_price' => 30.00,
                'group_discount_percent' => 5.00,
                'primary_image' => 'mount_talamitam.jpg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'business_id' => 7,
                'spot_name' => 'Club Punta Fuego',
                'description' => 'An exclusive resort offering world-class amenities, golf courses, and a private beach.',
                'category' => 'Resort',
                'location' => 'Balaytigue, Nasugbu, Batangas',
                'capacity' => 1000,
                'opening_time' => '07:00:00',
                'closing_time' => '22:00:00',
                'operating_days' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
                'status' => 'approved',
                'price_per_person' => 1200.00,
                'child_price' => 800.00,
                'senior_price' => 1000.00,
                'group_discount_percent' => 10.00,
                'primary_image' => 'club_punta_fuego.jpg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
          ],
           [
                'business_id' => 8,
                'spot_name' => 'Kaybiang Tunnel',
                'description' => 'The longest underground tunnel in the Philippines, connecting Ternate, Cavite and Nasugbu — ideal for scenic drives and cycling.',
                'category' => 'Landmark',
                'location' => 'Nasugbu-Ternate Highway, Nasugbu, Batangas',
                'capacity' => 1000,
                'opening_time' => '00:00:00',
                'closing_time' => '23:59:59',
                'operating_days' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
                'status' => 'approved',
                'price_per_person' => 0.00,
                'child_price' => 0.00,
                'senior_price' => 0.00,
                'group_discount_percent' => 0.00,
                'primary_image' => 'kaybiang_tunnel.jpg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
                'business_id' => 9,
                'spot_name' => 'Fortune Island',
                'description' => 'A stunning island featuring Greek-style ruins, white sand beaches, and turquoise waters ideal for snorkeling and diving.',
                'category' => 'Beach',
                'location' => 'Fortune Island, Nasugbu, Batangas',
                'capacity' => 300,
                'opening_time' => '06:00:00',
                'closing_time' => '18:00:00',
                'operating_days' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
                'status' => 'approved',
                'price_per_person' => 350.00,
                'child_price' => 200.00,
                'senior_price' => 250.00,
                'group_discount_percent' => 10.00,
                'primary_image' => 'fortune_island.jpg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
        ],
        [
                'business_id' => 9,
                'spot_name' => 'Laiya Beach',
                'description' => 'A popular beach destination known for its white sand, clear waters, and vibrant nightlife.',
                'category' => 'Beach',
                'location' => 'Laiya, San Juan, Batangas',
                'capacity' => 600,
                'opening_time' => '06:00:00',
                'closing_time' => '20:00:00',
                'operating_days' => 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
                'status' => 'approved',
                'price_per_person' => 400.00,
                'child_price' => 250.00,
                'senior_price' => 300.00,
                'group_discount_percent' => 10.00,
                'primary_image' => 'laiya_beach.jpg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],


            
        ];
        $this->db->table('tourist_spots')->insertBatch($data);

    }
}
