<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UserSeeder extends Seeder
{
    public function run()
    {
        //`UserID`, `FirstName`, `MiddleName`, `LastName`, `email`, `password`, `role`, `LastLogin`, `created_at`, `updated_at`

        $data = [
            [
                'FirstName' => 'Admin',
                'MiddleName' => 'A',
                'LastName' => 'User',
                'email' => 'admin@gmail.com',
                'password' => password_hash('admin123', PASSWORD_BCRYPT),
                'role' => 'Admin',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Spot',
                'MiddleName' => 'O',
                'LastName' => 'Owner',
                'email' => 'spot@gmail.com',
                'password' => password_hash('spot123', PASSWORD_BCRYPT),
                'role' => 'Spot Owner',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'FirstName' => 'Maria',
                'MiddleName' => 'B',
                'LastName' => 'Santos',
                'email' => 'maria.santos@gmail.com',
                'password' => password_hash('spot123', PASSWORD_BCRYPT),
                'role' => 'Spot Owner',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'FirstName' => 'Juan',
                'MiddleName' => 'R',
                'LastName' => 'Cruz',
                'email' => 'juan.cruz@gmail.com',
                'password' => password_hash('spot123', PASSWORD_BCRYPT),
                'role' => 'Spot Owner',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'FirstName' => 'Anna',
                'MiddleName' => 'L',
                'LastName' => 'Garcia',
                'email' => 'anna.garcia@gmail.com',
                'password' => password_hash('spot123', PASSWORD_BCRYPT),
                'role' => 'Spot Owner',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'FirstName' => 'Mark',
                'MiddleName' => 'T',
                'LastName' => 'Reyes',
                'email' => 'mark.reyes@gmail.com',
                'password' => password_hash('spot123', PASSWORD_BCRYPT),
                'role' => 'Spot Owner',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'FirstName' => 'Elaine',
                'MiddleName' => 'G',
                'LastName' => 'Tores',
                'email' => 'elaine.tores@gmail.com',
                'password' => password_hash('spot123', PASSWORD_BCRYPT),
                'role' => 'Spot Owner',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'FirstName' => 'Patric',
                'MiddleName' => 'V',
                'LastName' => 'Mendoza',
                'email' => 'patric.mendoza@gmail.com',
                'password' => password_hash('spot123', PASSWORD_BCRYPT),
                'role' => 'Spot Owner',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'FirstName' => 'Lara',
                'MiddleName' => 'C',
                'LastName' => 'Vilanueva',
                'email' => 'lara.vilanueva@gmail.com',
                'password' => password_hash('spot123', PASSWORD_BCRYPT),
                'role' => 'Spot Owner',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'FirstName' => 'Joseph',
                'MiddleName' => 'E',
                'LastName' => 'Mendoza',
                'email' => 'joseph.mendoza@gmail.com',
                'password' => password_hash('spot123', PASSWORD_BCRYPT),
                'role' => 'Spot Owner',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'FirstName' => 'Ryan',
                'MiddleName' => 'J',
                'LastName' => 'Ramos',
                'email' => 'ryan.ramoz@gmail.com',
                'password' => password_hash('spot123', PASSWORD_BCRYPT),
                'role' => 'Spot Owner',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
             [
                'FirstName' => 'Nicole',
                'MiddleName' => 'F',
                'LastName' => 'Lopez',
                'email' => 'nicole.lopez@gmail.com',
                'password' => password_hash('spot123', PASSWORD_BCRYPT),
                'role' => 'Spot Owner',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

//  tourist
// id start 13
            [
                'FirstName' => 'Carlos',
                'MiddleName' => 'D',
                'LastName' => 'Villanueva',
                'email' => 'carlos.villanueva@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Sofia',
                'MiddleName' => 'M',
                'LastName' => 'Delgado',
                'email' => 'sofian.delgado@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Miguel',
                'MiddleName' => 'A',
                'LastName' => 'Torres',
                'email' => 'miguel.tores@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Elena',
                'MiddleName' => 'S',
                'LastName' => 'Morales',
                'email' => 'elena.morales@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Andres',
                'MiddleName' => 'J',
                'LastName' => 'Cabrera',
                'email' => 'andres.cabrera@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Lucia',
                'MiddleName' => 'V',
                'LastName' => 'Serrano',
                'email' => 'lucia.serrano@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Diego',
                'MiddleName' => 'R',
                'LastName' => 'Navarro',
                'email' => 'diego.navarro@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Camila',
                'MiddleName' => 'L',
                'LastName' => 'Fuentes',
                'email' => 'camila.fuentes@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Javier',
                'MiddleName' => 'E',
                'LastName' => 'Silva',
                'email' => 'javier.silva@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Valeria',
                'MiddleName' => 'G',
                'LastName' => 'Ortiz',
                'email' => 'valeria.ortiz@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Fernando',
                'MiddleName' => 'M',
                'LastName' => 'Gomez',
                'email' => 'fernando.gomez@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Natalia',
                'MiddleName' => 'C',
                'LastName' => 'Rojas',
                'email' => 'natalia.rojas@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Sergio',
                'MiddleName' => 'T',
                'LastName' => 'Vega',
                'email' => 'sergio.vega@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Isabella',
                'MiddleName' => 'F',
                'LastName' => 'Silva',
                'email' => 'isabella.silva@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Ricardo',
                'MiddleName' => 'H',
                'LastName' => 'Mora',
                'email' => 'ricardo.mora@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Gabriela',
                'MiddleName' => 'N',
                'LastName' => 'Cortez',
                'email' => 'gabriela.cortez@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Matias',
                'MiddleName' => 'O',
                'LastName' => 'Salazar',
                'email' => 'matias.salazar@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Carmila',
                'MiddleName' => 'P',
                'LastName' => 'Duarte',
                'email' => 'carmila.duarte@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'FirstName' => 'Emilio',
                'MiddleName' => 'Q',
                'LastName' => 'Benitez',
                'email' => 'emilio.benitez@gmail.com',
                'password' => password_hash('tourist123', PASSWORD_BCRYPT),
                'role' => 'Tourist',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            
        



        ];
         $this->db->table('users')->insertBatch($data);


    }
}
