# Generated by Django 4.2 on 2025-10-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('num_adults', models.IntegerField()),
                ('num_children', models.IntegerField()),
                ('num_seniors', models.IntegerField()),
                ('total_guests', models.IntegerField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('booking_status', models.CharField(max_length=9)),
                ('payment_status', models.CharField(max_length=8)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('business_address', models.TextField()),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'businesses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=255)),
                ('class_field', models.CharField(db_column='class', max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('namespace', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
                ('batch', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(max_length=13)),
                ('payment_date', models.DateTimeField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=9)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RevenueAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('by_date', models.DateField(db_column='by_Date')),
                ('total_bookings', models.IntegerField()),
                ('confirmed_bookings', models.IntegerField()),
                ('cancelled_bookings', models.IntegerField()),
                ('total_visitors', models.IntegerField()),
                ('gross_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discounts', models.DecimalField(decimal_places=2, max_digits=15)),
                ('refunds', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_booking_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_party_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'revenue_analytics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('cleanliness_rating', models.IntegerField()),
                ('staff_rating', models.IntegerField()),
                ('value_rating', models.IntegerField()),
                ('location_rating', models.IntegerField()),
                ('status', models.CharField(max_length=8)),
                ('is_verified_visit', models.IntegerField()),
                ('owner_response', models.TextField(blank=True, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review_feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpotAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('available_date', models.DateField()),
                ('total_capacity', models.IntegerField()),
                ('booked_capacity', models.IntegerField()),
                ('available_capacity', models.IntegerField()),
                ('is_available', models.IntegerField()),
                ('reason_unavailable', models.CharField(blank=True, max_length=255, null=True)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spot_availability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpotGallery',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'spot_gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TouristSpots',
            fields=[
                ('spot_id', models.AutoField(primary_key=True, serialize=False)),
                ('spot_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('operating_days', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=17)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('senior_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group_discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('primary_image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tourist_spots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_preferences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=50, null=True)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=10)),
                ('lastlogin', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorCheckins',
            fields=[
                ('checkin_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('actual_visitors', models.IntegerField()),
                ('is_walkin', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visitor_checkins',
                'managed': False,
            },
        ),
    ]
